name: Test

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      liftbridge:
        image: liftbridge/standalone-dev:v1.5.1
        ports:
        - 9292:9292

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Unit test
      run: dotnet test test/Liftbridge.Net.UnitTests -c Release
    - name: Integration test
      run: dotnet test test/Liftbridge.Net.IntegrationTests -c Release